var trans_ja = {
    "name": "名前",
    "save": "保存",
    "language.english": "English",
    "language.japanese": "日本語",
    "category": "カテゴリ",
    "subcategory": "中項目",
    "selected": "選択済み",
    "download": "ダウンロード",
    "copy": "コピー",
    "freeInput": "フリー入力エリア",
    "alerts.nameMissing": "名前を入力してください。",
    "score_9": "score_9",
    "score_8": "score_8",
    "score_7": "score_7",
    "score_6": "score_6",
    "score_5": "score_5",
    "score_4": "score_4",
    "score_9_up": "score_9_up",
    "score_8_up": "score_8_up",
    "score_7_up": "score_7_up",
    "score_6_up": "score_6_up",
    "score_5_up": "score_5_up",
    "score_4_up": "score_4_up",
    "source_pony": "ウマの女の子（本当の馬に近い形状）",
    "source_furry": "ケモノ系のの女の子",
    "source_anime": "日本アニメ風",
    "source_cartoon": "カートゥーン",
    "rating_safe": "安全なコンテンツ",
    "rating_questionable": "ちょっと怪しいコンテンツ",
    "rating_explicit": "露骨なコンテンツ",
    "4k": "4K",
    "8k": "8K",
    "ultra highres": "超高解像度",
    "beautiful": "美しい",
    "exquisite": "素晴らしい",
    "masterpiece": "傑作",
    "best quality": "最高品質",
    "ultra quality": "超高品質",
    "detailed": "詳細",
    "extremely detailed": "非常に詳細",
    "finely detailed": "細かい",
    "insanely detailed": "非常に細かい",
    "ultra detailed": "超詳細",
    "low quality": "低品質",
    "worst quality": "最悪品質",
    "out of focus": "ピント外れ",
    "ugly": "醜い",
    "bokeh": "ボケ効果",
    "ugly face": "醜い顔",
    "partial face": "半分の顔",
    "partial head": "半分の頭",
    "bad face": "悪い顔",
    "cropped": "切り取られた",
    "error": "エラー",
    "JPEG artifacts": "JPEG劣化",
    "low resolution": "低解像度",
    "bad anatomy": "不正確な体",
    "long neck": "長い首",
    "deformed mutated disfigured": "変形",
    "missing arms": "欠けた腕",
    "extra arms": "追加の腕",
    "mutated hands": "変形した手",
    "extra legs": "追加の足",
    "bad hands": "悪い手",
    "poorly drawn hands": "下手な手",
    "malformed hands": "奇形の手",
    "missing limb": "欠けた四肢",
    "disconnected limbs": "繋がってない四肢",
    "extra fingers": "追加の指",
    "bad fingers": "悪い指",
    "liquid fingers": "溶けた指",
    "poorly drawn fingers": "下手な指",
    "missing fingers": "欠けた指",
    "extra digit": "追加の指",
    "fewer digits": "少ない指",
    "deformed eyes": "歪んだ目",
    "nsfw": "成人向け",
    "text": "テキスト",
    "signature": "署名",
    "watermark": "透かし",
    "username": "ユーザー名",
    "artist name": "アーティスト名",
    "stamp": "スタンプ",
    "title, subtitle": "タイトル",
    "date": "日付",
    "blush": "赤面",
    "open mouth": "口開け",
    "make-up": "化粧",
    "mascara": "マスカラ",
    "rouge": "口紅",
    "half-open eyes": "半開きの目",
    "closed mouth": "口閉じ",
    "multiple angle": "複数角度",
    "two shot": "二人画面",
    "split view": "分割画面",
    "grid view": "グリッド表示",
    "Laughing": "笑う",
    "Chuckling": "くすくす",
    "Delighted": "喜ぶ",
    "Excited": "興奮",
    "smirk": "にやり",
    "Jubilant": "嬉々",
    "Smiling": "笑顔",
    "Rejoicing": "喜び",
    "Joyful": "幸せ",
    "Bashful": "はにかむ",
    "smug": "得意",
    "Elated": "大喜び",
    "Angry": "怒り",
    "Indignant": "憤り",
    "Enraged": "激怒",
    "Frustrated": "悔しがる",
    "Infuriated": "怒り",
    "Resentful": "怨み",
    "Aggressive": "攻撃的",
    "Antagonistic": "敵意",
    "disdain": "軽蔑",
    "Outraged": "憤慨",
    "Yelling": "怒鳴り",
    "Complaining": "不平",
    "Hostile": "敵意",
    "Scowling": "怒り顔",
    "Hateful": "憎しみ",
    "Shouting": "怒号",
    "Annoyed": "イライラ",
    "Saddened": "悲しみ",
    "Grieving": "心痛",
    "Disheartened": "落胆",
    "Suffering": "苦しみ",
    "Pained": "痛み",
    "despair": "絶望",
    "Tearful": "涙ぐむ",
    "Painful": "つらい",
    "Melancholic": "憂鬱",
    "Sobbing": "すすり泣き",
    "Heavy-hearted": "心重い",
    "shy": "照れる",
    "red cheek": "赤面",
    "nose blush": "鼻赤面",
    "bashful": "はにかむ",
    "blush stickers": "ブラッシュ",
    "embarrassed": "恥ずかしい",
    "full-face blush": "全顔赤面",
    "worried": "心配",
    "nervous": "緊張",
    "stressed": "緊張",
    "scared": "怖い",
    "stupefied": "うろたえ",
    "surprised": "驚く",
    "shocked": "ショック",
    "stunned": "呆然",
    "painful": "苦しい",
    "regrettable": "悔しい",
    "disdain/contempt": "軽蔑",
    "disgust/disgusted": "嫌悪",
    "evil smile/evil grin": "悪い笑顔",
    "grimace": "顔を歪める",
    "repulsed": "反発",
    "wince": "苦痛顔",
    "one eye closed": "片目閉じ",
    "eyes closed": "目閉じ",
    "twinkle": "きらり",
    "sparkle": "輝く",
    "watery eyes": "涙目",
    "half closed eyes": "半目",
    "tareme": "たれ目",
    "tsurime": "つり目",
    "cute eyes": "可愛い目",
    "close-mouth": "口閉じ",
    "open-mouth": "口開け",
    "full lips": "ふっくら唇",
    "thin lips": "薄い唇",
    "plump lips": "ぽってり唇",
    "toothless smile": "歯なし笑顔",
    "wide smile": "広い笑顔",
    "toothy grin": "歯見せ笑顔",
    "closed-mouth smile": "口閉じ笑顔",
    "gummy smile": "歯茎見せ笑顔",
    "straight teeth": "歯並び良い",
    "straight nose": "直鼻",
    "upturned nose": "上向き鼻",
    "snub nose": "短鼻",
    "long nose": "長鼻",
    "short nose": "短鼻",
    "wide nose": "広い鼻",
    "narrow nose": "細い鼻",
    "flat nose": "平鼻",
    "bulging nose": "膨らんだ鼻",
    "concave nose": "凹鼻",
    "pointed nose": "尖鼻",
    "rounded nose": "丸鼻",
    "angular nose": "角鼻",
    "Looking at Viewer": "カメラ目線",
    "Staring Intently": "じっと見つめる",
    "Looking Side Glance": "横を見る",
    "Looking Over Shoulder": "肩越しに見る",
    "Looking Back": "振り返る",
    "Gazing into the Distance": "遠くを見つめる",
    "Gazing Skyward": "空を見る",
    "Eyes Closed": "目閉じ",
    "Gazing at Something Off-Frame": "フレーム外を見る",
    "Glancing Elsewhere": "他をちらっと見る",
    "Turning Head Away": "頭をそらす",
    "Gazing Upward": "上を見つめる",
    "Looking Up": "上を見る",
    "from front": "正面",
    "from above": "上",
    "from below": "下",
    "from side": "横",
    "from behind": "後ろ",
    "blunt bangs": "前髪ぱっつん",
    "hair over one eye": "片目隠れ",
    "hime cut": "姫カット",
    "parted bang": "分け目前髪",
    "forehead": "センター分け",
    "asymmetrical bangs": "非対称前髪",
    "ponytail": "ポニー",
    "side ponytail": "サイドポニー",
    "half updo": "ハーフアップ",
    "one side up": "片側アップ",
    "two side up": "両側アップ",
    "twintails": "ツイン",
    "low twintails": "ローツイン",
    "short twintails": "ショートツイン",
    "pixie cut": "短髪",
    "short hair": "ショート",
    "medium hair": "ミディアム",
    "long hair": "ロング",
    "ahoge": "アホ毛",
    "messy hair": "くせ毛",
    "flipped hair": "外ハネ",
    "curly inside hair": "内巻き",
    "ringlets": "リングレット",
    "hair bun": "お団子",
    "red hair": "赤髪",
    "orange hair": "オレンジ髪",
    "yellow hair": "黄色髪",
    "green hair": "緑髪",
    "blue hair": "青髪",
    "purple hair": "紫髪",
    "white hair": "白髪",
    "black hair": "黒髪",
    "Shirt": "シャツ",
    "Short-sleeved shirt": "半袖シャツ",
    "Shirt button": "シャツボタン",
    "Casual shirt": "カジュアルシャツ",
    "Polo shirt": "ポロシャツ",
    "V-neck shirt": "Vネック",
    "knit sweater": "ニット",
    "Long-sleeved knit": "長袖ニット",
    "Cardigan": "カーディガン",
    "Chunky knit sweater": "チャンキーニット",
    "Ribbed knit": "リブニット",
    "Crewneck sweater": "クルーネック",
    "Jacket": "ジャケット",
    "Coat": "コート",
    "Pea Coat": "ピーコート",
    "Biker Jacket": "バイカー",
    "Denim Jacket": "デニム",
    "Bomber Jacket": "ボンバー",
    "Raincoat": "レインコート",
    "Double-breasted": "ダブル",
    "Field Jacket": "フィールド",
    "Anorak": "アノラック",
    "Shorts": "ショーツ",
    "Cargo pants": "カーゴパンツ",
    "Leggings": "レギンス",
    "Sweatpants": "スウィートパンツ",
    "Straight cut": "ストレート",
    "High-waisted": "ハイウエスト",
    "Wide Leg Pants": "ワイドパンツ",
    "Jeans": "ジーンズ",
    "Slim fit": "スリム",
    "Boot cut": "ブーツカット",
    "Low-waisted": "ローウエスト",
    "A-line skirt": "Aライン",
    "Beach-shorts": "ビーチショーツ",
    "Cargo-pants": "カーゴパンツ",
    "Checked-skirt": "チェックスカート",
    "Denim skirt": "デニム",
    "Hakama-pants": "袴",
    "Leather-pants": "レザーパンツ",
    "Long skirt": "ロングスカート",
    "Low-rise-shorts": "ロウライズショーツ",
    "Micro-mini-skirt": "マイクロミニ",
    "Mini skirt": "ミニスカート",
    "Pencil skirt": "タイト",
    "Pleated skirt": "プリーツ",
    "Ruffle skirt": "らっふるスカート",
    "Short-pants-denim": "ショートパンツデニム",
    "Tutu": "チュチュ",
    "One-piece": "ワンピース",
    "Shift Dress": "シフトドレス",
    "Wrap Dress": "ラップドレス",
    "Pencil Dress": "ペンシル",
    "Halterneck Dress": "ホルター",
    "Maxi Dress": "マキシ",
    "Mini Dress": "ミニドレス",
    "Sundress": "サンドレス",
    "Cocktail Dress": "カクテル",
    "Empire Dress": "エンパイア",
    "tall": "高い",
    "towering": "そびえる",
    "lanky": "手足長い",
    "leggy": "脚長い",
    "heightened": "高い",
    "elongated": "長い",
    "enormous": "巨大",
    "gigantic": "巨大",
    "giant": "巨大",
    "petite": "小柄",
    "tiny": "非常に小さい",
    "height-challenged": "低い",
    "short": "低い",
    "diminutive": "小柄",
    "dwarf": "小人",
    "below average": "平均以下",
    "out of proportion": "不均衡",
    "short stature": "小柄",
    "short height": "低い",
    "overweight": "太った",
    "obese": "肥満",
    "chubby": "ぽっちゃり",
    "plump": "ふっくら",
    "rotund": "丸々",
    "portly": "太った",
    "corpulent": "肥満",
    "slim": "細い",
    "fit": "健康的",
    "medium": "標準",
    "slender": "細身",
    "underweight": "痩せ",
    "skinny": "痩せ",
    "scrawny": "やせすぎ",
    "baby": "赤ちゃん",
    "infant": "幼児",
    "toddler": "幼児",
    "very young child": "幼い子",
    "child": "子供",
    "10 years old": "10歳",
    "15 years old": "15歳",
    "18 years old": "18歳",
    "college age": "大学生",
    "20 years old": "20歳",
    "young adult": "若者",
    "30 years old": "30歳",
    "thirties": "30代",
    "40 years old": "40歳",
    "forties": "40代",
    "50 years old": "50歳",
    "age fifties": "50代",
    "60 years old": "60歳",
    "70 years old": "70歳",
    "pale skin": "白肌",
    "fair skin": "色白",
    "dark skin": "黒肌",
    "tan skin": "日焼け肌",
    "tanned skin": "日焼け",
    "tanlines": "日焼け跡",
    "wheat skin": "小麦肌",
    "shiny skin": "つや肌",
    "oiled skin": "油肌",
    "gloss skin": "光沢肌",
    "glistening skin": "輝く肌",
    "detailed skin": "細かい肌",
    "porcelain skin": "陶器肌",
    "wet skin": "濡れ肌",
    "suntan": "日焼け",
    "sweaty skin": "汗肌",
    "wrinkles skin": "しわ肌",
    "No-makeup look": "メイクなし",
    "Heavy makeup": "厚化粧",
    "Light makeup": "薄化粧",
    "Natural makeup": "自然",
    "full makeup": "フルメイク",
    "Glamorous makeup": "グラマラス",
    "Matte finish makeup": "マット仕上げ",
    "Dewy finish makeup": "つや仕上げ",
    "thick eyebrow": "濃い眉",
    "thin eyebrow": "薄い眉",
    "Eyeshadow": "アイシャドウ",
    "Mascara": "マスカラ",
    "Eyeliner": "アイライナー",
    "False eyelashes": "つけまつげ",
    "Lash extensions": "まつげエクステ",
    "Cheek": "チーク",
    "Bronzer": "ブロンザー",
    "Highlighter": "ハイライト",
    "red lips": "赤い唇",
    "pink lips": "ピンクの唇",
    "orange lips": "オレンジの唇",
    "sneakers": "スニーカー",
    "sandals": "サンダル",
    "high-heels": "ハイヒール",
    "pumps": "パンプス",
    "long boots": "ロングブーツ",
    "ankle boots": "ショートブーツ",
    "loafers": "ローファー",
    "leather shoes": "革靴",
    "Running shoes": "ランニングシューズ",
    "rain boots": "レインブーツ",
    "pantyhose": "パンスト",
    "thigh-high socks": "太もも丈",
    "knee-high socks": "膝丈",
    "calf socks": "ふくらはぎ丈",
    "ankle socks": "くるぶし丈",
    "1 boy, 2 girls": "1男2女",
    "many boys, many girls": "多男多女",
    "1 girl and 1 boy": "1女1男",
    "1 father and 1 child": "父と子",
    "group of friends": "友達グループ",
    "couple": "カップル",
    "classmates": "クラスメート",
    "team of XX": "XXチーム",
    "group of students": "学生グループ",
    "raise arm": "片腕上げ",
    "arms up": "両腕上げ",
    "arms behind back": "腕を後ろに",
    "cross arms in front": "腕を組む",
    "hand on hip": "手を腰に",
    "peace sign": "ピース",
    "spread arms": "腕を広げる",
    "praying hands": "手を合わせる",
    "clenched fist": "拳を握る",
    "hand on chest": "胸に手",
    "pointing finger": "指さし",
    "thumbs up": "グッド",
    "sitting": "座る",
    "standing": "立つ",
    "squatting": "しゃがむ",
    "cross-legged": "足を組む",
    "lying on back": "仰向け",
    "legs spread": "足を広げる",
    "seiza": "正座",
    "jumping": "ジャンプ",
    "running": "走る",
    "waving": "手を振る",
    "walking and waving": "歩きながら手を振る",
    "punching": "パンチ",
    "selfie": "自撮り",
    "singing": "歌う",
    "dutch angle": "斜め",
    "full body": "全身",
    "upper body": "上半身",
    "face close-up": "顔アップ",
    "cowboy shot": "腰から上",
    "clear sky": "晴れた空",
    "sunrise": "日の出",
    "dawn": "明け方",
    "in the morning": "朝",
    "in the noon": "昼",
    "in the evening": "夕方",
    "in the night": "夜",
    "cloud": "曇り",
    "rain": "雨",
    "snowy": "雪",
    "forest": "森",
    "cherry blossoms": "桜",
    "river": "川",
    "mountain": "山",
    "island": "島",
    "ocean": "海",
    "sandy beach": "砂浜",
    "snow mountain": "雪山",
    "cave": "洞窟",
    "boat": "船",
    "kitchen": "キッチン",
    "living": "リビング",
    "room": "部屋",
    "closet": "クローゼット",
    "japanese-style room": "和室",
    "garden": "庭",
    "school": "学校",
    "super market": "スーパー",
    "coffee shop": "カフェ",
    "restaurant": "レストラン",
    "shopping mall": "ショッピングモール",
    "market": "市場",
    "skyscraper": "高層ビル",
    "shopping street": "商店街",
    "supermarket": "スーパー",
    "department store": "デパート",
    "cafe": "カフェ",
    "cinema": "映画館",
    "club": "クラブ",
    "hotel": "ホテル",
    "bar": "バー",
    "art gallery": "美術館",
    "hospital": "病院",
    "bank": "銀行",
    "library": "図書館",
    "police station": "警察署",
    "airport": "空港",
    "museum": "博物館",
    "city hall": "市役所",
    "shrine": "神社・寺院",
    "post office": "郵便局",
    "park": "公園",
    "bus stop": "バス停",
    "backlighting": "背後からの光",
    "spotlight": "スポットライト",
    "sidelighting": "横からの光",
    "underlighting": "下からの光",
    "stage lights": "ステージライト",
    "volumetric lighting": "ボリューム光",
    "cinematic lighting": "映画的な光",
    "rim lighting": "輪郭光",
    "dynamic lighting": "動的な光",
    "sunlight": "太陽光",
    "dimly light": "薄暗い光",
    "crepuscular rays": "光線",
    "strong light": "強い光",
    "light sparkles": "輝く光",
    "faint light": "弱い光",
    "moonlight": "月明かり",
    "darkness": "暗闇",
    "black": "黒",
    "charcoal gray": "チャコール",
    "ivory black": "アイボリー",
    "white": "白",
    "gray": "灰",
    "taupe": "トープ",
    "snow white": "雪白",
    "milky white": "乳白",
    "pearl white": "真珠白",
    "silver": "銀",
    "red": "赤",
    "crimson": "クリムゾン",
    "garnet": "ガーネット",
    "magenta": "マゼンタ",
    "rose red": "バラ赤",
    "ruby": "ルビー",
    "scarlet": "スカーレット",
    "strawberry": "ストロベリー",
    "wine red": "ワイン赤",
    "azalea": "ツツジ",
    "orange": "オレンジ",
    "apricot": "アプリコット",
    "burnt sienna": "焦げシエナ",
    "cinnamon": "シナモン",
    "tangerine": "タンジェリン",
    "vermilion": "朱色",
    "persimmon orange": "柿オレンジ",
    "brown": "茶",
    "bister": "ビスタ",
    "camel": "キャメル",
    "chocolate": "チョコレート",
    "hazel brown": "ヘーゼル",
    "henna": "ヘナ",
    "khaki": "カーキ",
    "sepia": "セピア",
    "terracotta": "テラコッタ",
    "umber": "アンバー",
    "yellow": "黄",
    "beige": "ベージュ",
    "blond": "金",
    "maize": "トウモロコシ",
    "primrose yellow": "プリムローズ黄",
    "marigold": "マリーゴールド",
    "green": "緑",
    "aquamarine": "アクアマリン",
    "celadon": "青磁",
    "emerald": "エメラルド",
    "forest green": "森緑",
    "leaf green": "葉緑",
    "viridian": "ビリジアン",
    "blue": "青",
    "aqua": "水色",
    "cerulean": "空色",
    "cyan": "シアン",
    "frosty blue": "淡青",
    "indigo": "藍",
    "navy blue": "紺",
    "ultramarine": "群青",
    "wedgewood blue": "ウェッジウッド",
    "azure": "蒼",
    "purple": "紫",
    "claret": "深赤",
    "crocus": "紫花",
    "iris": "菖蒲",
    "lavender": "ラベンダー",
    "violet": "紫羅",
    "wistaria": "藤",
    "peony": "牡丹",
    "vector art": "ベクター",
    "watercolor": "水彩",
    "line art": "線画",
    "gouache": "ガッシュ",
    "ink drawing": "インク",
    "pixel art": "ピクセル",
    "flat design": "フラット",
    "sketch": "スケッチ",
    "digital painting": "デジタル",
    "3d model": "3D",
    "manga style": "マンガ",
    "pop art": "ポップ",
    "photorealistic": "写実",
    "impasto": "厚塗り",
    "thick paint": "厚塗り",
    "oil painting": "油絵",
    "pastel": "パステル",
    "chiaroscuro": "明暗",
    "contour drawing": "輪郭",
    "silhouette": "影絵",
    "low poly": "ローポリ",
    "anime style": "アニメ",
    "comic style": "コミック",
    "realistic": "リアル"
}